[package]
name = "unity_code_native"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.29"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tower-lsp = "0.20"
tree-sitter = "0.20"
tree-sitter-css = "0.20"
